name: femunity
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.00.00

environment:
  sdk: ">=2.19.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  flutter_riverpod: ^2.2.0
  url_launcher: ^6.1.10
  fpdart: ^0.4.1
  routemaster: ^1.0.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.5
  shared_preferences: ^2.0.18
  uuid: ^3.0.7
  any_link_preview: ^3.0.0
  flutter_hooks: ^0.18.6
  flutter_test:
    sdk: flutter
  delayed_display: ^2.0.0
  animations: ^2.0.7
  animated_widgets: ^1.1.0
  flutter_animations: ^0.0.1+10
  animated_text_kit: ^4.2.2
  liquid_swipe: ^3.0.0
  flutter_keyboard_visibility: ^5.4.0
  transparent_image: ^2.0.1
  profanity_filter: ^2.0.0
  geolocator: ^9.0.2
  location: ^4.4.0
  convert: ^3.1.1
  http: ^0.13.5
  share: ^2.0.4
  flutter_spinkit: ^5.1.0
  permission_handler: ^10.2.0

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/gdsc.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: femFont
      fonts:
        - asset: assets/fonts/femFont.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Horizon
      fonts:
        - asset: assets/fonts/Horizon-regular.ttf
        - asset: assets/fonts/Horizon-regular-italic.ttf
        - asset: assets/fonts/Horizon-bold-italic.ttf
        - asset: assets/fonts/Horizon-bold.ttf

    - family: FutureLight
      fonts:
        - asset: assets/fonts/FutureLight-BW15w.ttf
        - asset: assets/fonts/FutureLightItalic-1GeEv.ttf

    - family: Scrip
      fonts:
        - asset: assets/fonts/SCRIPALT.ttf
        - asset: assets/fonts/SCRIPTIN.ttf

    - family: AlBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
